[package]
name = "rakuga"
version = "0.1.0"
edition = "2024"

[dependencies]
fontdue = "0.9"

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"] }

[[example]]
name = "display"
path = "examples/display.rs"
